import { Category, Transaction, Budget, SavingsGoal } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  // Expenses
  { id: 'cat-food', name: 'Ăn uống', type: 'expense', icon: 'Utensils', color: '#f59e0b' },
  { id: 'cat-bills', name: 'Hóa đơn & Nhà ở', type: 'expense', icon: 'Home', color: '#ef4444' },
  { id: 'cat-transport', name: 'Di chuyển', type: 'expense', icon: 'Car', color: '#3b82f6' },
  { id: 'cat-shopping', name: 'Mua sắm', type: 'expense', icon: 'ShoppingBag', color: '#ec4899' },
  { id: 'cat-entertainment', name: 'Giải trí & Phim', type: 'expense', icon: 'Film', color: '#8b5cf6' },
  { id: 'cat-health', name: 'Sức khỏe & Y tế', type: 'expense', icon: 'HeartPulse', color: '#10b981' },
  { id: 'cat-education', name: 'Học tập & Sách', type: 'expense', icon: 'GraduationCap', color: '#06b6d4' },
  { id: 'cat-other-exp', name: 'Chi phí khác', type: 'expense', icon: 'MoreHorizontal', color: '#64748b' },

  // Income
  { id: 'cat-salary', name: 'Lương hàng tháng', type: 'income', icon: 'Wallet', color: '#10b981' },
  { id: 'cat-freelance', name: 'Thưởng & Freelance', type: 'income', icon: 'Briefcase', color: '#6366f1' },
  { id: 'cat-investment', name: 'Lợi nhuận đầu tư', type: 'income', icon: 'TrendingUp', color: '#f59e0b' },
  { id: 'cat-other-inc', name: 'Thu nhập khác', type: 'income', icon: 'PlusCircle', color: '#14b8a6' },
];

export const INITIAL_MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    user_id: 'demo-user',
    type: 'income',
    amount: 25000000,
    category_id: 'cat-salary',
    category_name: 'Lương hàng tháng',
    category_icon: 'Wallet',
    category_color: '#10b981',
    note: 'Nhận lương công ty tháng này',
    date: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tx-2',
    user_id: 'demo-user',
    type: 'expense',
    amount: 5500000,
    category_id: 'cat-bills',
    category_name: 'Hóa đơn & Nhà ở',
    category_icon: 'Home',
    category_color: '#ef4444',
    note: 'Tiền thuê nhà + điện nước internet',
    date: new Date(new Date().getFullYear(), new Date().getMonth(), 3).toISOString().split('T')[0],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tx-3',
    user_id: 'demo-user',
    type: 'expense',
    amount: 3200000,
    category_id: 'cat-food',
    category_name: 'Ăn uống',
    category_icon: 'Utensils',
    category_color: '#f59e0b',
    note: 'Tiền đi chợ, siêu thị & cà phê',
    date: new Date(new Date().getFullYear(), new Date().getMonth(), 5).toISOString().split('T')[0],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tx-4',
    user_id: 'demo-user',
    type: 'income',
    amount: 4000000,
    category_id: 'cat-freelance',
    category_name: 'Thưởng & Freelance',
    category_icon: 'Briefcase',
    category_color: '#6366f1',
    note: 'Thanh toán dự án thiết kế website',
    date: new Date(new Date().getFullYear(), new Date().getMonth(), 7).toISOString().split('T')[0],
    created_at: new Date().toISOString(),
  },
  {
    id: 'tx-5',
    user_id: 'demo-user',
    type: 'expense',
    amount: 1500000,
    category_id: 'cat-shopping',
    category_name: 'Mua sắm',
    category_icon: 'ShoppingBag',
    category_color: '#ec4899',
    note: 'Mua quần áo mới & phụ kiện',
    date: new Date(new Date().getFullYear(), new Date().getMonth(), 8).toISOString().split('T')[0],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_MOCK_BUDGETS: Budget[] = [
  {
    id: 'bgt-1',
    user_id: 'demo-user',
    category_id: 'cat-food',
    category_name: 'Ăn uống',
    category_icon: 'Utensils',
    category_color: '#f59e0b',
    monthly_limit: 6000000,
  },
  {
    id: 'bgt-2',
    user_id: 'demo-user',
    category_id: 'cat-shopping',
    category_name: 'Mua sắm',
    category_icon: 'ShoppingBag',
    category_color: '#ec4899',
    monthly_limit: 3000000,
  },
  {
    id: 'bgt-3',
    user_id: 'demo-user',
    category_id: 'cat-entertainment',
    category_name: 'Giải trí & Phim',
    category_icon: 'Film',
    category_color: '#8b5cf6',
    monthly_limit: 2000000,
  },
];

export const INITIAL_MOCK_SAVINGS: SavingsGoal[] = [
  {
    id: 'svg-1',
    user_id: 'demo-user',
    title: 'Quỹ Dự Phòng Khẩn Cấp (6 tháng)',
    target_amount: 50000000,
    current_amount: 32000000,
    target_date: '2026-12-31',
    category_color: '#10b981',
    icon: 'ShieldCheck',
  },
  {
    id: 'svg-2',
    user_id: 'demo-user',
    title: 'Đổi Laptop Mới (MacBook Pro)',
    target_amount: 45000000,
    current_amount: 28000000,
    target_date: '2026-10-15',
    category_color: '#6366f1',
    icon: 'Laptop',
  },
  {
    id: 'svg-3',
    user_id: 'demo-user',
    title: 'Chuyến Du Lịch Nhật Bản',
    target_amount: 30000000,
    current_amount: 12000000,
    target_date: '2027-04-01',
    category_color: '#ec4899',
    icon: 'Plane',
  },
];
